import assert from "node:assert/strict";
import { readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";
import test from "node:test";

test("the public fixture is generated by the real detector", () => {
  const output = join(tmpdir(), `argus-demo-${process.pid}.json`);
  const result = spawnSync(
    process.execPath,
    [new URL("./generate-demo-fixture.mjs", import.meta.url).pathname, output],
    { encoding: "utf8" },
  );

  assert.equal(result.status, 0, result.stderr);
  const fixture = JSON.parse(readFileSync(output, "utf8"));
  const run = fixture.runs[0];
  const finding = fixture.decisions[run.id][0];

  assert.equal(fixture.metadata.label, "Bundled demo data");
  assert.equal(fixture.metadata.rows, 21);
  assert.equal(fixture.metrics[run.id].length, 21);
  assert.deepEqual(
    finding.anomaly_types.map(({ type }) => type),
    ["grad_explosion", "loss_spike"],
  );
  assert.equal(finding.status, "detected");
  assert.equal(finding.fixed, null);
  assert.match(fixture.metadata.scope, /No model API, backend, Supabase, or repair action/);
  rmSync(output);
});
